# Colors = solarized dark
[colors.bright]
black = "0x002b36"
blue = "0x839496"
cyan = "0x93a1a1"
green = "0x586e75"
magenta = "0x6c71c4"
red = "0xcb4b16"
white = "0xfdf6e3"
yellow = "0x657b83"

[colors.normal]
black = "0x073642"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0xeee8d5"
yellow = "0xb58900"

[colors.primary]
# Darker background
background = "0x002b36"
foreground = "0x839496"

[env]
# Fix ssh colors
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "FuraMono Nerd Font"
style = "Bold"

[font.italic]
family = "FuraMono Nerd Font"
style = "Italic"

[font.normal]
family = "FuraMono Nerd Font"
style = "Regular"

# Launch with zellij
[terminal.shell]
args = ['-l', '-c', '/home/will/.cargo/bin/zellij']
program = "/usr/bin/fish"

[window]
decorations = "none"
startup_mode = "Maximized"

[terminal]
